development:
  adapter: postgresql
  database: rails-rspec_dev
  host: localhost
  encoding: UTF8
  min_messages: WARNING

test: &test
  adapter: postgresql
  database: rails-rspec_test
  host: localhost
  encoding: UTF8
  min_messages: WARNING

production:
  adapter: postgresql
  database: rails-rspec_production
  pool: 5
  timeout: 5000